### PR TITLE
Added a fix to check if the clicked inventory is the GUI and not player's own inventory

### PR DESCRIPTION
**Pull request by MCreeper12731**
Addresses issue: [https://github.com/SamJakob/SpiGUI/issues/19](url)

### CODE REVIEW

**Comment by SamJakob** [comment]
Hi, Thanks for your PR!
I just noticed that I use event.getInventory instead of event.getClickedInventory on lines 28 - are you able to see if removing your new check and swapping getInventory with getClickedInventory work?

**Comment by MCreeper12731** [comment]
Changed according to the instructions. There needs to be an additional check if clicked inventory is not null (occurs when the player clicks outside of the inventory UI)

**Comment by SamJakob** [comment]
All good, thanks! Did you get a chance to test this?

**Comment by MCreeper12731** [comment]
Yes, tested, and it now works only if you click in the GUI. I can send a video if you need proof

**Comment by SamJakob** [comment]
Nope that's good enough for me! Thank you :)

**Pull request merged**
